\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={TelecomChurnCapstone},
            pdfauthor={Nirmal Patel},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{TelecomChurnCapstone}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Nirmal Patel}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{November 10, 2018}


\begin{document}
\maketitle

\section{Introduction}\label{introduction}

The telecommunication industry has come a long way since its beginning
of being just a phone service industry. Once the telephone became mobile
over 45 years ago, technological advances have skyrocketed. This has
forced the major companies to accommodate and increase its client base
by adding more services to make their store a one-stop-shop for all
their technological needs. Over time, telephone companies have had to
increase many more products and services. Products include tablets,
watches, smartphones, flip-phones, home-security monitors, and even
voice controlled speakers. While the services include Phone, Internet,
Online Security, Online Backup, Device Protection, Tech Support, and
even Streaming TV/ Movies. The data from these companies can be useful
in customer retention in order to minimize the number of customers
leaving the company.

\section{Disclaimer}\label{disclaimer}

The data provided does not contain any personal information of customers
such as name, address, phone number and location. To keep this anonymity
a Customer ID number was provided by IBM.

\subsection{\texorpdfstring{Dataset:
\url{https://www.ibm.com/communities/analytics/watson-analytics-blog/guide-to-sample-datasets/}}{Dataset: https://www.ibm.com/communities/analytics/watson-analytics-blog/guide-to-sample-datasets/}}\label{dataset-httpswww.ibm.comcommunitiesanalyticswatson-analytics-blogguide-to-sample-datasets}

\section{Data}\label{data}

The dataset consists of 147,924 entries with 7044 rows and 21 columns.
The column variables and their descriptions are:

\begin{longtable}[]{@{}ll@{}}
\toprule
\begin{minipage}[b]{0.22\columnwidth}\raggedright\strut
Variable\strut
\end{minipage} & \begin{minipage}[b]{0.72\columnwidth}\raggedright\strut
Description\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
customerID\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
Customer ID\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
genderCustomer\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
Gender (female, male)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
SeniorCitizen\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
Whether the customer is a senior citizen or not (1, 0)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
PartnerWhether\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
The customer has a partner or not (Yes, No)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
DependentsWhether\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
The customer has dependents or not (Yes, No)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
tenure\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
Number of months the customer has stayed with the company\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
PhoneService\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
Whether the customer has a phone service or not (Yes, No)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
MultipleLines\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
Whether the customer has multiple lines or not (Yes, No, No phone
service)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
InternetService\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
Customer's internet service provider (DSL, Fiber optic, No)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
OnlineSecurity\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
Whether the customer has online security or not (Yes, No, No internet
service)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
OnlineBackup\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
Whether the customer has online backup or not (Yes, No, No internet
service)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
DeviceProtection\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
Whether the customer has device protection or not (Yes, No, No internet
service)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
TechSupport\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
Whether the customer has tech support or not (Yes, No, No internet
service)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
StreamingTV\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
Whether the customer has streaming TV or not (Yes, No, No internet
service)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
StreamingMovies\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
Whether the customer has streaming movies or not (Yes, No, No internet
service)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
Contract\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
The contract term of the customer (Month-to-month, One year, Two
year)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
PaperlessBilling\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
Whether the customer has paperless billing or not (Yes, No)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
PaymentMethod\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
The customer's payment method (Electronic check, Mailed check, Bank
transfer (automatic), Credit card (automatic))\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
MonthlyCharges\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
The amount charged to the customer monthly\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
TotalCharges\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
The total amount charged to the customer\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.22\columnwidth}\raggedright\strut
ChurnWhether\strut
\end{minipage} & \begin{minipage}[t]{0.72\columnwidth}\raggedright\strut
The customer churned or not (Yes or No)\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\section{Data Wrangling}\label{data-wrangling}

I loaded the dataset as a CSV file and renamed it telecom and added
necessary libraries to it. In this section, I looked for outliers,
missing values, and if the variable was crucial for the customer churn
analysis.

\subsection{Structure}\label{structure}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(telecom)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    7043 obs. of  21 variables:
##  $ customerID      : Factor w/ 7043 levels "0002-ORFBO","0003-MKNFE",..: 5376 3963 2565 5536 6512 6552 1003 4771 5605 4535 ...
##  $ gender          : Factor w/ 2 levels "Female","Male": 1 2 2 2 1 1 2 1 1 2 ...
##  $ SeniorCitizen   : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ Partner         : Factor w/ 2 levels "No","Yes": 2 1 1 1 1 1 1 1 2 1 ...
##  $ Dependents      : Factor w/ 2 levels "No","Yes": 1 1 1 1 1 1 2 1 1 2 ...
##  $ tenure          : int  1 34 2 45 2 8 22 10 28 62 ...
##  $ PhoneService    : Factor w/ 2 levels "No","Yes": 1 2 2 1 2 2 2 1 2 2 ...
##  $ MultipleLines   : Factor w/ 3 levels "No","No phone service",..: 2 1 1 2 1 3 3 2 3 1 ...
##  $ InternetService : Factor w/ 3 levels "DSL","Fiber optic",..: 1 1 1 1 2 2 2 1 2 1 ...
##  $ OnlineSecurity  : Factor w/ 3 levels "No","No internet service",..: 1 3 3 3 1 1 1 3 1 3 ...
##  $ OnlineBackup    : Factor w/ 3 levels "No","No internet service",..: 3 1 3 1 1 1 3 1 1 3 ...
##  $ DeviceProtection: Factor w/ 3 levels "No","No internet service",..: 1 3 1 3 1 3 1 1 3 1 ...
##  $ TechSupport     : Factor w/ 3 levels "No","No internet service",..: 1 1 1 3 1 1 1 1 3 1 ...
##  $ StreamingTV     : Factor w/ 3 levels "No","No internet service",..: 1 1 1 1 1 3 3 1 3 1 ...
##  $ StreamingMovies : Factor w/ 3 levels "No","No internet service",..: 1 1 1 1 1 3 1 1 3 1 ...
##  $ Contract        : Factor w/ 3 levels "Month-to-month",..: 1 2 1 2 1 1 1 1 1 2 ...
##  $ PaperlessBilling: Factor w/ 2 levels "No","Yes": 2 1 2 1 2 2 2 1 2 1 ...
##  $ PaymentMethod   : Factor w/ 4 levels "Bank transfer (automatic)",..: 3 4 4 1 3 3 2 4 3 1 ...
##  $ MonthlyCharges  : num  29.9 57 53.9 42.3 70.7 ...
##  $ TotalCharges    : num  29.9 1889.5 108.2 1840.8 151.7 ...
##  $ Churn           : Factor w/ 2 levels "No","Yes": 1 1 2 1 2 2 1 1 2 1 ...
\end{verbatim}

The structure of the telecom company depicts four variables that are
integers or numerical type. It would be beneficial if we look into these
and see if there are any NA or blank variables. We can also see that
most of the data is well organized and has 2 to 4 factors. This data
looks clean with well defined variable names.

\section{Data Exploration}\label{data-exploration}

\subsection{Summary of Telecom Churn
Data}\label{summary-of-telecom-churn-data}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(telecom)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       customerID      gender     SeniorCitizen    Partner    Dependents
##  0002-ORFBO:   1   Female:3488   Min.   :0.0000   No :3641   No :4933  
##  0003-MKNFE:   1   Male  :3555   1st Qu.:0.0000   Yes:3402   Yes:2110  
##  0004-TLHLJ:   1                 Median :0.0000                        
##  0011-IGKFF:   1                 Mean   :0.1621                        
##  0013-EXCHZ:   1                 3rd Qu.:0.0000                        
##  0013-MHZWF:   1                 Max.   :1.0000                        
##  (Other)   :7037                                                       
##      tenure      PhoneService          MultipleLines     InternetService
##  Min.   : 0.00   No : 682     No              :3390   DSL        :2421  
##  1st Qu.: 9.00   Yes:6361     No phone service: 682   Fiber optic:3096  
##  Median :29.00                Yes             :2971   No         :1526  
##  Mean   :32.37                                                          
##  3rd Qu.:55.00                                                          
##  Max.   :72.00                                                          
##                                                                         
##              OnlineSecurity              OnlineBackup 
##  No                 :3498   No                 :3088  
##  No internet service:1526   No internet service:1526  
##  Yes                :2019   Yes                :2429  
##                                                       
##                                                       
##                                                       
##                                                       
##             DeviceProtection              TechSupport  
##  No                 :3095    No                 :3473  
##  No internet service:1526    No internet service:1526  
##  Yes                :2422    Yes                :2044  
##                                                        
##                                                        
##                                                        
##                                                        
##               StreamingTV              StreamingMovies
##  No                 :2810   No                 :2785  
##  No internet service:1526   No internet service:1526  
##  Yes                :2707   Yes                :2732  
##                                                       
##                                                       
##                                                       
##                                                       
##            Contract    PaperlessBilling                   PaymentMethod 
##  Month-to-month:3875   No :2872         Bank transfer (automatic):1544  
##  One year      :1473   Yes:4171         Credit card (automatic)  :1522  
##  Two year      :1695                    Electronic check         :2365  
##                                         Mailed check             :1612  
##                                                                         
##                                                                         
##                                                                         
##  MonthlyCharges    TotalCharges    Churn     
##  Min.   : 18.25   Min.   :  18.8   No :5174  
##  1st Qu.: 35.50   1st Qu.: 401.4   Yes:1869  
##  Median : 70.35   Median :1397.5             
##  Mean   : 64.76   Mean   :2283.3             
##  3rd Qu.: 89.85   3rd Qu.:3794.7             
##  Max.   :118.75   Max.   :8684.8             
##                   NA's   :11
\end{verbatim}

The summary function gives us a further break down of the variables
including the mean(average), minimum(smallest value), median (middle
value), maximum(largest value), and if the variable includes a blank
value (NA) this function will let us know. If the variable is a factor,
the summary method will give us the total of each factor.

The tenure variable is given in number of months. It does not have and
blank or NA values. The maximum tenure that the data included was 72
months.

The monthly charges range from \$18.25 to \$118.75. There are no blanks
or NA values.

\subsection{Summary of Telecom Total
Charges}\label{summary-of-telecom-total-charges}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(telecom}\OperatorTok{$}\NormalTok{TotalCharges)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##    18.8   401.4  1397.5  2283.3  3794.7  8684.8      11
\end{verbatim}

The total charges range from \$18.8 to \$8684.8, the max seems very high
it could possibly be an outlier. This variable also has 11 blank points.
Therefore we will have to determine if removing the rows with blanks
would be better than keeping them. I decided to keep them in my data for
now. but would use the omit function if needed to remove them. We have
11 NA out of 7043 points.

\subsection{Compare Total and Monthly
Charges}\label{compare-total-and-monthly-charges}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{compare<-}\StringTok{ }\KeywordTok{mutate}\NormalTok{(telecom,}\DataTypeTok{TotalDivide12=}\NormalTok{TotalCharges}\OperatorTok{/}\DecValTok{12}\NormalTok{)}
\NormalTok{compare1<-}\KeywordTok{select}\NormalTok{(compare,MonthlyCharges,TotalCharges,TotalDivide12)}
\NormalTok{compare1[}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    MonthlyCharges TotalCharges TotalDivide12
## 1           29.85        29.85       2.48750
## 2           56.95      1889.50     157.45833
## 3           53.85       108.15       9.01250
## 4           42.30      1840.75     153.39583
## 5           70.70       151.65      12.63750
## 6           99.65       820.50      68.37500
## 7           89.10      1949.40     162.45000
## 8           29.75       301.90      25.15833
## 9          104.80      3046.05     253.83750
## 10          56.15      3487.95     290.66250
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#removing TotalCharges}
\NormalTok{telecom}\OperatorTok{$}\NormalTok{TotalCharges=}\OtherTok{NULL}
\end{Highlighting}
\end{Shaded}

We need to perform a check to see if the monthly charges are equal to
the total charges divided by 12. The number 12 is used because there are
12 months in a year. From the looks of the total charges column is not
uniform and has some charges that might be monthly and some that might
be yearly and of various time frames, therefore it makes more sense to
omit this column for two reasons: missing values and unstructured method
of calculating the total.

\subsection{gender}\label{gender}

\emph{Are men more likely to have coverage?}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{telecomwork1<-telecom}
\NormalTok{pie <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(telecomwork1, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =} \StringTok{""}\NormalTok{, }\DataTypeTok{fill =} \KeywordTok{factor}\NormalTok{(gender))) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{width =} \DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.line =} \KeywordTok{element_blank}\NormalTok{(), }
        \DataTypeTok{plot.title =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{hjust=}\FloatTok{0.5}\NormalTok{)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{fill=}\StringTok{"class"}\NormalTok{, }
       \DataTypeTok{x=}\OtherTok{NULL}\NormalTok{, }
       \DataTypeTok{y=}\OtherTok{NULL}\NormalTok{, }
       \DataTypeTok{title=}\StringTok{"Customer Gender"}\NormalTok{, }
       \DataTypeTok{subtitle=}\StringTok{"Female= 49.5%  |  Male= 50.5%"}\NormalTok{)}
  
\NormalTok{pie }\OperatorTok{+}\StringTok{ }\KeywordTok{coord_polar}\NormalTok{(}\DataTypeTok{theta =} \StringTok{"y"}\NormalTok{, }\DataTypeTok{start=}\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{TelecomChurnCapstoneReport_files/figure-latex/genders,-1.pdf}

We have 48.5\% Female and 50.5\% Male in our data. Therefore the data
seems normally distributed and large enough to be unbiased.

\subsection{Gender and Monthly
Charges}\label{gender-and-monthly-charges}

\emph{Does one gender pay more monthly charges?}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(telecom,}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{gender,}\DataTypeTok{y=}\NormalTok{MonthlyCharges))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_boxplot}\NormalTok{(}\DataTypeTok{varwidth=}\NormalTok{T, }\DataTypeTok{fill=}\DecValTok{23}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_hline}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{yintercept =} \KeywordTok{median}\NormalTok{(telecom}\OperatorTok{$}\NormalTok{MonthlyCharges)), }\DataTypeTok{color =} \StringTok{"green"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{"Gender"}\NormalTok{,}\DataTypeTok{y=}\StringTok{"Monthly Charges in Dollars"}\NormalTok{,}\DataTypeTok{title=}\StringTok{"Gender and Monthly Charges of Customers"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{TelecomChurnCapstoneReport_files/figure-latex/gendernmonthcharge-1.pdf}
The data shows that both male and female monthly costs were about the
same with a median of \$70.35 represented by the green line. This seems
fair and impartial toward a particular sex getting an immense discount.

\subsection{Payment}\label{payment}

\emph{What is the most common form of payment?}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{paymethods <-}\StringTok{ }\NormalTok{telecom }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(PaymentMethod) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{PaymentMethod_count =} \KeywordTok{n}\NormalTok{()) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(PaymentMethod_count))}
\NormalTok{paymethods}\OperatorTok{$}\NormalTok{PaymentMethod <-}\StringTok{ }\KeywordTok{factor}\NormalTok{(paymethods}\OperatorTok{$}\NormalTok{PaymentMethod, }\DataTypeTok{levels =}\NormalTok{ paymethods}\OperatorTok{$}\NormalTok{PaymentMethod[}\KeywordTok{order}\NormalTok{((paymethods}\OperatorTok{$}\NormalTok{PaymentMethod_count))])}
\NormalTok{colourCount =}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(paymethods}\OperatorTok{$}\NormalTok{PaymentMethod))}
\NormalTok{fill_purple <-}\StringTok{ }\KeywordTok{colorRampPalette}\NormalTok{(}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{,}\StringTok{"BuPu"}\NormalTok{))}

\NormalTok{paymethods }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(PaymentMethod }\OperatorTok{!=}\StringTok{ "NA"}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ PaymentMethod, }\DataTypeTok{y =}\NormalTok{ PaymentMethod_count, }\DataTypeTok{fill =}\NormalTok{ PaymentMethod)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{coord_flip}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ PaymentMethod_count), }\DataTypeTok{size =} \FloatTok{2.5}\NormalTok{, }\DataTypeTok{color =} \StringTok{"black"}\NormalTok{, }\DataTypeTok{hjust =} \OperatorTok{-}\NormalTok{.}\DecValTok{5}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{"Payment"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"Number of Customers"}\NormalTok{, }\DataTypeTok{title =} \StringTok{"Methods of Payment Used by Customers"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position =} \StringTok{"none"}\NormalTok{, }\DataTypeTok{plot.title =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\KeywordTok{max}\NormalTok{(paymethods}\OperatorTok{$}\NormalTok{PaymentMethod_count }\OperatorTok{+}\StringTok{ }\DecValTok{100}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values =} \KeywordTok{fill_purple}\NormalTok{(colourCount))}
\end{Highlighting}
\end{Shaded}

\includegraphics{TelecomChurnCapstoneReport_files/figure-latex/paymeth-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(telecom}\OperatorTok{$}\NormalTok{PaymentMethod))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Bank transfer (automatic)   Credit card (automatic) 
##                 0.2192248                 0.2161011 
##          Electronic check              Mailed check 
##                 0.3357944                 0.2288797
\end{verbatim}

The Most common form of payment was Electronic check accounting for
33.5\%. Second most common was Mailed check at 22.9\%. Third was Bank
transfer (automatic) at 22\%. Least common was Credit card (automatic)
at 21.6\%.

\subsection{Monthly charges}\label{monthly-charges}

\emph{What is the range of monthly charges?}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(telecom}\OperatorTok{$}\NormalTok{MonthlyCharges)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   18.25   35.50   70.35   64.76   89.85  118.75
\end{verbatim}

The monthly charges range from \$18.25 to \$118.75 per month. The
mean/average monthly bill is \$64.76. While the median bill is \$70.35.

\subsection{Senior Citizen's}\label{senior-citizens}

\emph{Do senior citizens get a discount? Are there more senior
customers? }

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(telecom,}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{SeniorCitizen,}\DataTypeTok{y=}\NormalTok{MonthlyCharges, }\DataTypeTok{color=}\NormalTok{gender))}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_jitter}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{"Senior Citizens"}\NormalTok{,}\DataTypeTok{y=}\StringTok{"MonthlyCharges"}\NormalTok{,}\DataTypeTok{title=}\StringTok{"Monthly charges per senior customer"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{TelecomChurnCapstoneReport_files/figure-latex/seniorcitmonthpay-1.pdf}

The telecom company seems to have about the same minimum and maximum
monthly charges as for the Senior citizens as the regular non senior
customers. However, the majority of Senior Citizens seem to be paying
above \textasciitilde{}\$70. Therefore it seems that being a senior does
not give a bonus to all customers. We would have to do a bar plot to see
the difference between number of senior and non-senior customers to see
how many people we have in each group.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gendersenir <-}\StringTok{ }\NormalTok{telecom }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(SeniorCitizen) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{dplyr}\OperatorTok{::}\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{SeniorCitizen_count =} \KeywordTok{n}\NormalTok{()) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(SeniorCitizen_count))}
\NormalTok{gendersenir}\OperatorTok{$}\NormalTok{SeniorCitizen <-}\StringTok{ }\KeywordTok{factor}\NormalTok{(gendersenir}\OperatorTok{$}\NormalTok{SeniorCitizen, }\DataTypeTok{levels =}\NormalTok{ gendersenir}\OperatorTok{$}\NormalTok{SeniorCitizen[}\KeywordTok{order}\NormalTok{((gendersenir}\OperatorTok{$}\NormalTok{SeniorCitizen_count))])}
\NormalTok{colourCount =}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(gendersenir}\OperatorTok{$}\NormalTok{SeniorCitizen))}
\NormalTok{fill_purple <-}\StringTok{ }\KeywordTok{colorRampPalette}\NormalTok{(}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{,}\StringTok{"BuPu"}\NormalTok{))}

\NormalTok{gendersenir }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(SeniorCitizen }\OperatorTok{!=}\StringTok{ "NA"}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ SeniorCitizen, }\DataTypeTok{y =}\NormalTok{ SeniorCitizen_count, }\DataTypeTok{fill =}\NormalTok{ SeniorCitizen)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{coord_flip}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ SeniorCitizen_count), }\DataTypeTok{size =} \DecValTok{3}\NormalTok{, }\DataTypeTok{color =} \StringTok{"black"}\NormalTok{, }\DataTypeTok{hjust =} \OperatorTok{-}\NormalTok{.}\DecValTok{5}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{"Payment"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"Number of Customers"}\NormalTok{, }\DataTypeTok{title =} \StringTok{"Methods of Payment Used by Customers"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position =} \StringTok{"none"}\NormalTok{, }\DataTypeTok{plot.title =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\KeywordTok{max}\NormalTok{(gendersenir}\OperatorTok{$}\NormalTok{SeniorCitizen_count }\OperatorTok{+}\StringTok{ }\DecValTok{100}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values =} \KeywordTok{fill_purple}\NormalTok{(colourCount))}
\end{Highlighting}
\end{Shaded}

\includegraphics{TelecomChurnCapstoneReport_files/figure-latex/gendersenir-1.pdf}
There are very few Senior Customers in comparison to non-senior
customers. There are more that 5x non senior customers (purple) in
comparison to senior customers (white).

\subsection{Ecofriendly/ Paperless}\label{ecofriendly-paperless}

\emph{How eco friendly is the brand? Does it have a higher percentage of
paperless billing?}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(telecom,}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{PaperlessBilling,}\DataTypeTok{fill=}\NormalTok{gender))}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{ () }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{"Paperless"}\NormalTok{,}\DataTypeTok{y=}\StringTok{"Number of Customers"}\NormalTok{,}\DataTypeTok{title=}\StringTok{"Gender and Paperless Service"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{TelecomChurnCapstoneReport_files/figure-latex/ecobill-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(telecom}\OperatorTok{$}\NormalTok{PaperlessBilling))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##        No       Yes 
## 0.4077808 0.5922192
\end{verbatim}

About 59\% of customers choose the paperless route, while 41\% still
want a paper copy of the bill. This can be improved by giving an
incentive to go paperless, which would save the company on stationary
supplies such as paper, ink, and postage.

\subsection{CustomerTenure}\label{customertenure}

\emph{Which months are critical for keeping the customer?}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{g <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(telecom, }\KeywordTok{aes}\NormalTok{(tenure)) }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_fill_brewer}\NormalTok{(}\DataTypeTok{palette =} \DecValTok{1}\NormalTok{)}


\NormalTok{g }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_histogram}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{fill=}\NormalTok{gender), }
                   \DataTypeTok{bins=}\DecValTok{10}\NormalTok{, }
                   \DataTypeTok{col=}\StringTok{"blue"}\NormalTok{, }
                   \DataTypeTok{size=}\NormalTok{.}\DecValTok{1}\NormalTok{) }\OperatorTok{+}\StringTok{   }\CommentTok{# change number of bins}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title=}\StringTok{"Histogram of tenure plotted by gender"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{TelecomChurnCapstoneReport_files/figure-latex/customertenure-1.pdf}
There seems to be an equal amount of tenure/retention between male and
female customers. It also seems that after 40 months the customer is
more likely to stay. However from 0 to 40 months it seems that the
customer is likely to churn and the company should focus on retaining
their customers during this period.

\subsection{Gender and Phoneservice}\label{gender-and-phoneservice}

\emph{Is a particular gender more likely to have a phone service with
our company}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(telecom,}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{gender,}\DataTypeTok{fill=}\NormalTok{PhoneService))}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{ () }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{"Gender"}\NormalTok{,}\DataTypeTok{y=}\StringTok{"Number of Customers"}\NormalTok{,}\DataTypeTok{title=}\StringTok{"Gender and Phone Service of Customers"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{TelecomChurnCapstoneReport_files/figure-latex/genderandphoneservice-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(telecom}\OperatorTok{$}\NormalTok{gender, telecom}\OperatorTok{$}\NormalTok{PhoneService))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         
##                  No        Yes
##   Female 0.04699702 0.44824649
##   Male   0.04983672 0.45491978
\end{verbatim}

44.8\% women have a phone service with our company while 4.7\% women do
not. 45.5\% male customers have the phone service, while 5\% male do not
have the phone service.

\subsection{Gender and Preferred Type of
Payment}\label{gender-and-preferred-type-of-payment}

\emph{Do more men or women prefer each type of contract? Month-to-month,
One year, Two year?}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(telecom,}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{gender,}\DataTypeTok{y=}\NormalTok{Contract, }\DataTypeTok{color=}\NormalTok{gender))}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_jitter}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_grid}\NormalTok{(.}\OperatorTok{~}\NormalTok{Churn)}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{"Gender"}\NormalTok{,}\DataTypeTok{y=}\StringTok{"Contract Type"}\NormalTok{,}\DataTypeTok{title=}\StringTok{"Contract Type based on Gender"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{TelecomChurnCapstoneReport_files/figure-latex/gendernContract-1.pdf}
There seems to be an equal number of male and women per Contract type.
However by adding a Churn statistics to this data we see that the month
to month customers where most likely to churn while, One year
contractees were less likely to churn and Two year contractees were
least likely to churn.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{( telecom}\OperatorTok{$}\NormalTok{Contract))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Month-to-month       One year       Two year 
##      0.5501917      0.2091438      0.2406645
\end{verbatim}

The most common contract type is month to month at 55\% total, followed
by Two year contract at 24\%, and least common was one year contract at
21\% of total contracts.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(telecom}\OperatorTok{$}\NormalTok{gender, telecom}\OperatorTok{$}\NormalTok{Contract))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         
##          Month-to-month  One year  Two year
##   Female      0.2733210 0.1019452 0.1199773
##   Male        0.2768707 0.1071986 0.1206872
\end{verbatim}

The data shows that about 27\% male and 27\% female have a month to
month contract. While 10\% female and 11\% male have a One year
contract. And 12\% females and 12\% males have a two year contract.

\subsection{Internet or Phone sells
more}\label{internet-or-phone-sells-more}

\emph{What is more common phone service or internet service?}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(telecom,}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{InternetService,}\DataTypeTok{y=}\NormalTok{PhoneService,}\DataTypeTok{color=}\NormalTok{gender))}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_jitter}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{"InternetService"}\NormalTok{,}\DataTypeTok{y=}\StringTok{"PhoneService"}\NormalTok{,}\DataTypeTok{title=}\StringTok{"InternetService vs. PhoneService"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{TelecomChurnCapstoneReport_files/figure-latex/internetvphoen-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(telecom}\OperatorTok{$}\NormalTok{InternetService, telecom}\OperatorTok{$}\NormalTok{PhoneService))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              
##                       No        Yes
##   DSL         0.09683374 0.24691183
##   Fiber optic 0.00000000 0.43958540
##   No          0.00000000 0.21666903
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(telecom}\OperatorTok{$}\NormalTok{InternetService))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##         DSL Fiber optic          No 
##   0.3437456   0.4395854   0.2166690
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{( telecom}\OperatorTok{$}\NormalTok{PhoneService))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##         No        Yes 
## 0.09683374 0.90316626
\end{verbatim}

78.3\% of the customers have Internet service while 90\% have phone
service. Therefore Phone service is more common. This may lead to the
company having to work more on marketing a better way to increase
internet sales.

\subsection{Internet Sales}\label{internet-sales}

\emph{Which types of internet service are most commonly bought?}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{telecomwork<-telecom}
\NormalTok{pie2 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(telecomwork, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =} \StringTok{""}\NormalTok{, }\DataTypeTok{fill =} \KeywordTok{factor}\NormalTok{(InternetService))) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{width =} \DecValTok{1}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.line =} \KeywordTok{element_blank}\NormalTok{(), }
        \DataTypeTok{plot.title =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{hjust=}\FloatTok{0.5}\NormalTok{)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{fill=}\StringTok{"class"}\NormalTok{, }
       \DataTypeTok{x=}\OtherTok{NULL}\NormalTok{, }
       \DataTypeTok{y=}\OtherTok{NULL}\NormalTok{, }
       \DataTypeTok{title=}\StringTok{"Internet Service Sales"}\NormalTok{, }
       \DataTypeTok{subtitle=}\StringTok{"DSL =34%, Fiber Optic =44%, No =22%"}\NormalTok{)}
  
\NormalTok{pie2 }\OperatorTok{+}\StringTok{ }\KeywordTok{coord_polar}\NormalTok{(}\DataTypeTok{theta =} \StringTok{"y"}\NormalTok{, }\DataTypeTok{start=}\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{TelecomChurnCapstoneReport_files/figure-latex/INTERNETS-1.pdf}
The internet Service sales indicate that customers chose DSL = 34\%,
Fiber Optic = 44\%, and No internet service = 22\% of the times.

\subsection{gender and Churn}\label{gender-and-churn}

\emph{What percentage of customers stay based on gender?}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(telecom,}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{gender,}\DataTypeTok{fill=}\NormalTok{Churn))}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{ () }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{"Gender"}\NormalTok{,}\DataTypeTok{y=}\StringTok{"Number of Customers"}\NormalTok{,}\DataTypeTok{title=}\StringTok{"Gender and Churn of Customers"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{TelecomChurnCapstoneReport_files/figure-latex/gendernchurn -1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(telecom}\OperatorTok{$}\NormalTok{gender, telecom}\OperatorTok{$}\NormalTok{Churn))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         
##                 No       Yes
##   Female 0.3619196 0.1333239
##   Male   0.3727105 0.1320460
\end{verbatim}

About 26.5\% of customers churned of these 13.3\% where female while
13.2\% were male. While 73.5\% customers stayed with our telecom
company. Of these customers 36.2\% where female and 37.3\% where male.

\section{Machine Learning}\label{machine-learning}

\subsection{Logistic Regression}\label{logistic-regression}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{churnmodel <-}\StringTok{ }\KeywordTok{glm}\NormalTok{(Churn}\OperatorTok{~}\NormalTok{gender}\OperatorTok{+}\NormalTok{SeniorCitizen}\OperatorTok{+}\NormalTok{Partner}\OperatorTok{+}\NormalTok{Dependents}\OperatorTok{+}\NormalTok{tenure}\OperatorTok{+}\NormalTok{PhoneService}\OperatorTok{+}\NormalTok{MultipleLines}\OperatorTok{+}\NormalTok{InternetService}\OperatorTok{+}\NormalTok{OnlineSecurity}\OperatorTok{+}\NormalTok{OnlineBackup}\OperatorTok{+}\NormalTok{DeviceProtection}\OperatorTok{+}\NormalTok{TechSupport}\OperatorTok{+}\NormalTok{StreamingTV}\OperatorTok{+}\NormalTok{StreamingMovies}\OperatorTok{+}\NormalTok{Contract}\OperatorTok{+}\NormalTok{PaperlessBilling}\OperatorTok{+}\NormalTok{PaymentMethod}\OperatorTok{+}\NormalTok{MonthlyCharges,}\DataTypeTok{data=}\NormalTok{telecom, }\DataTypeTok{family=}\StringTok{"binomial"}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(churnmodel)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = Churn ~ gender + SeniorCitizen + Partner + Dependents + 
##     tenure + PhoneService + MultipleLines + InternetService + 
##     OnlineSecurity + OnlineBackup + DeviceProtection + TechSupport + 
##     StreamingTV + StreamingMovies + Contract + PaperlessBilling + 
##     PaymentMethod + MonthlyCharges, family = "binomial", data = telecom)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.9780  -0.6707  -0.2946   0.6918   3.1454  
## 
## Coefficients: (7 not defined because of singularities)
##                                       Estimate Std. Error z value Pr(>|z|)
## (Intercept)                           0.612080   0.811986   0.754  0.45097
## genderMale                           -0.020514   0.064885  -0.316  0.75189
## SeniorCitizen                         0.217015   0.084920   2.556  0.01060
## PartnerYes                           -0.002440   0.077741  -0.031  0.97496
## DependentsYes                        -0.167071   0.089678  -1.863  0.06246
## tenure                               -0.034172   0.002366 -14.443  < 2e-16
## PhoneServiceYes                       0.165499   0.652460   0.254  0.79976
## MultipleLinesNo phone service               NA         NA      NA       NA
## MultipleLinesYes                      0.462796   0.178054   2.599  0.00934
## InternetServiceFiber optic            1.720069   0.803709   2.140  0.03234
## InternetServiceNo                    -1.622325   0.811846  -1.998  0.04568
## OnlineSecurityNo internet service           NA         NA      NA       NA
## OnlineSecurityYes                    -0.199497   0.179719  -1.110  0.26698
## OnlineBackupNo internet service             NA         NA      NA       NA
## OnlineBackupYes                       0.049975   0.176251   0.284  0.77676
## DeviceProtectionNo internet service         NA         NA      NA       NA
## DeviceProtectionYes                   0.162576   0.177303   0.917  0.35918
## TechSupportNo internet service              NA         NA      NA       NA
## TechSupportYes                       -0.168836   0.181586  -0.930  0.35248
## StreamingTVNo internet service              NA         NA      NA       NA
## StreamingTVYes                        0.593806   0.328488   1.808  0.07065
## StreamingMoviesNo internet service          NA         NA      NA       NA
## StreamingMoviesYes                    0.608397   0.328840   1.850  0.06429
## ContractOne year                     -0.666321   0.106644  -6.248 4.15e-10
## ContractTwo year                     -1.356836   0.173956  -7.800 6.20e-15
## PaperlessBillingYes                   0.335906   0.074277   4.522 6.12e-06
## PaymentMethodCredit card (automatic) -0.086598   0.114085  -0.759  0.44782
## PaymentMethodElectronic check         0.314319   0.094582   3.323  0.00089
## PaymentMethodMailed check            -0.005299   0.113719  -0.047  0.96283
## MonthlyCharges                       -0.032716   0.031940  -1.024  0.30570
##                                         
## (Intercept)                             
## genderMale                              
## SeniorCitizen                        *  
## PartnerYes                              
## DependentsYes                        .  
## tenure                               ***
## PhoneServiceYes                         
## MultipleLinesNo phone service           
## MultipleLinesYes                     ** 
## InternetServiceFiber optic           *  
## InternetServiceNo                    *  
## OnlineSecurityNo internet service       
## OnlineSecurityYes                       
## OnlineBackupNo internet service         
## OnlineBackupYes                         
## DeviceProtectionNo internet service     
## DeviceProtectionYes                     
## TechSupportNo internet service          
## TechSupportYes                          
## StreamingTVNo internet service          
## StreamingTVYes                       .  
## StreamingMoviesNo internet service      
## StreamingMoviesYes                   .  
## ContractOne year                     ***
## ContractTwo year                     ***
## PaperlessBillingYes                  ***
## PaymentMethodCredit card (automatic)    
## PaymentMethodElectronic check        ***
## PaymentMethodMailed check               
## MonthlyCharges                          
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 8150.1  on 7042  degrees of freedom
## Residual deviance: 5851.0  on 7020  degrees of freedom
## AIC: 5897
## 
## Number of Fisher Scoring iterations: 6
\end{verbatim}

The most significant variables were SeniorCitizen, tenure,
MultipleLines, InternetService, Contract, PaperlessBilling, and
PaymentMethod.

\subsection{ROC}\label{roc}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{##accuracy}
\NormalTok{ROCReval<-}\StringTok{ }\KeywordTok{performance}\NormalTok{(ROCRpred, }\StringTok{"acc"}\NormalTok{)}
\KeywordTok{plot}\NormalTok{(ROCReval)}
\KeywordTok{abline}\NormalTok{(}\DataTypeTok{h=}\FloatTok{0.805}\NormalTok{, }\DataTypeTok{v=}\FloatTok{0.53}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{TelecomChurnCapstoneReport_files/figure-latex/TESTACCURACY -1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#returns true if prediction greater than 0.5 predictsChurn and false for less than 0.5 predicts stay}
\KeywordTok{table}\NormalTok{(telecomTrain}\OperatorTok{$}\NormalTok{Churn,predictTrainn}\OperatorTok{>}\FloatTok{0.53}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      
##       FALSE TRUE
##   No   3545  335
##   Yes   676  726
\end{verbatim}

With a cutoff of 0.53.The true positive rate is 726/(335+726)= 0.6843,
So 68.43\% of the time the model can predict a customer will churn and
they would churn. While False Positive rate is 676/(676+3545)= 0.1602,
so 16.02\% the model would predict a customer will churn though they
stayed. The accuracy of the model is (3545+726)/(3545+335+676+726)=
0.8086. This model has an accuracy of 80.86\%

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#ROC Curve}
\NormalTok{ROCRpred<-}\KeywordTok{prediction}\NormalTok{(predictTrainn,telecomTrain}\OperatorTok{$}\NormalTok{Churn)}

\NormalTok{ROCRperf<-}\StringTok{ }\KeywordTok{performance}\NormalTok{(ROCRpred, }\StringTok{"tpr"}\NormalTok{,}\StringTok{"fpr"}\NormalTok{)}

\KeywordTok{plot}\NormalTok{(ROCRperf, }\DataTypeTok{colorize=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{print.cutoffs.at=}\KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{,}\FloatTok{0.1}\NormalTok{),}\DataTypeTok{text.adj=}\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\FloatTok{0.2}\NormalTok{,}\FloatTok{1.7}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{TelecomChurnCapstoneReport_files/figure-latex/ROCCUERV-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{AUC<-}\KeywordTok{performance}\NormalTok{(ROCRpred, }\StringTok{"auc"}\NormalTok{)}
\NormalTok{AUC<-}\KeywordTok{unlist}\NormalTok{(}\KeywordTok{slot}\NormalTok{(AUC,}\StringTok{"y.values"}\NormalTok{))}
\NormalTok{AUC<-}\KeywordTok{round}\NormalTok{(AUC,}\DecValTok{4}\NormalTok{)}
\NormalTok{AUC}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8475
\end{verbatim}

The area under the curve of our model is 0.8475. Our model has an
accuracy of 84.75\% which is really good.\\
\#Predicting Churning on Multiple Variables

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{churnmodel1 <-}\StringTok{ }\KeywordTok{glm}\NormalTok{(Churn}\OperatorTok{~}\NormalTok{gender}\OperatorTok{+}\NormalTok{SeniorCitizen}\OperatorTok{+}\NormalTok{tenure}\OperatorTok{+}\NormalTok{MonthlyCharges}\OperatorTok{+}\NormalTok{MultipleLines}\OperatorTok{+}\NormalTok{InternetService}\OperatorTok{+}\NormalTok{Contract}\OperatorTok{+}\NormalTok{PaperlessBilling}\OperatorTok{+}\NormalTok{PaymentMethod,}\DataTypeTok{data=}\NormalTok{telecom, }\DataTypeTok{family=}\StringTok{"binomial"}\NormalTok{)}





\KeywordTok{plot}\NormalTok{(}\KeywordTok{allEffects}\NormalTok{(churnmodel1))}
\end{Highlighting}
\end{Shaded}

\includegraphics{TelecomChurnCapstoneReport_files/figure-latex/HYPOUTTRANSx-1.pdf}

\section{Conclusion}\label{conclusion}

The telecom customer churn analysis depicts various interesting results
some of which include: 1. Females are \textasciitilde{}0.2\% more likely
to churn\\
2. Senior Citizens are \textasciitilde{}4\% likely to churn\\
3. Customers with tenure of 0 months are \textasciitilde{}40\% more
likely to churn compared to customers with tenure of 72 months. Between
0 to 40 months the customer is likely to churn. The company should focus
on their services during this period. 4. Higher monthly charges to
customers are more likely to churn. A customer paying \$100 monthly is
1.75x more likely to churn than that of a customer paying
\textasciitilde{}\$20 per month\\
5. Customers with multiple lines are 1.3x more likely to churn compared
to people with no multiple lines (single line). Customers with no phone
service are 1.9x more likely to churn in comparison with single line
service. 6. Customers with Fiber Optics are 2.7x more likely to churn in
comparison to customers with no internet service. While DSL customers
are 1.4x likely to churn compared to customers with no internet service.
7. Month to Month customers are 3.5x more likely to churn than a two
year contracted customer. While a one year contracted customer is 1.8x
more likely to churn than a two year contracted customer.\\
8. Customers with paperless billing are 1.37x more likely to churn than
those receiving their monthly bill in the mail.\\
9. Customers paying with Electronic Check are 1.4x more likely to churn
in comparison to customers paying in credit card. While customers paying
by bank transfer were 1.07x and customers paying by mailed check was
1.03x more likely to churn in comparison to customers paying in credit
card.

\section{Recommendations}\label{recommendations}

More research would need to be done to see if these trends are specific
to this data set or can be used to speak of other telecom data sets as
well. Addition of detailed variables to this data such as price of each
service, the location of the customer, demography, and age of customer
would help gain further insight.


\end{document}
